[project]
name = "xpublish-ogc-core"
version = "0.1.0"
description = "OGC API Common structure and support for OGC Xpublish plugins"
readme = "README.md"
authors = [
    { name = "Alex Kerney", email = "abk@mac.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2",
    "xpublish>=0.4.1"
]

[dependency-groups]
dev = [
    "cf-xarray",
    "httpx",
    "jsonschema",
    "netcdf4",
    "pooch",
    "pytest",
    "referencing",
    "schemathesis>=4",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[project.entry-points."xpublish.plugin"]
xpublish_ogc_core = "xpublish_ogc_core.plugin:OgcCorePlugin"
